In [1]:
import numpy as np
import cv2
import glob
import pdb
from matplotlib import pyplot as plt
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((9*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:9].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('cal1.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (7,9),None)
#     pdb.set_trace()
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (7,6), corners2,ret)
        cv2.imwrite('cal_board.png',img)
#         plt.imshow(img)
#         plt.show()
#         cv2.imshow('img',img)
#         cv2.waitKey(500)
#         pdb.set_trace()
# cv2.destroyAllWindows()

In [2]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)


In [3]:
img = cv2.imread('Current_frame.jpg')
h,  w = img.shape[:2]
newcameramtx, roi=cv2.getOptimalNewCameraMatrix(mtx,dist,(w,h),1,(w,h))
print(h)

298


In [4]:
# undistort
dst = cv2.undistort(img, mtx, dist, None, newcameramtx)
print(roi)
# crop the image
x,y,w,h = roi
dst = dst[y:y+h, x:x+w]
print(dst)
cv2.imwrite('Current_frame_dist.png',dst)

(40, 32, 239, 235)
[[[  3   8  13]
  [  4  14  22]
  [  6  17  26]
  ...
  [ 44  75  90]
  [ 45  76  91]
  [ 47  76  91]]

 [[  4  12  19]
  [  6  16  25]
  [  3  15  24]
  ...
  [ 56  82  98]
  [ 57  82  98]
  [ 59  82  99]]

 [[  8  15  22]
  [  9  20  27]
  [  7  18  25]
  ...
  [ 56  78  93]
  [ 58  78  93]
  [ 58  78  92]]

 ...

 [[138 165 199]
  [137 164 198]
  [137 164 198]
  ...
  [127 152 178]
  [133 158 184]
  [137 162 188]]

 [[138 165 199]
  [137 164 198]
  [137 164 198]
  ...
  [126 151 177]
  [131 156 182]
  [133 158 184]]

 [[137 164 198]
  [137 164 198]
  [137 164 198]
  ...
  [126 151 177]
  [133 158 184]
  [137 162 188]]]


True